
project_id = "cmzhdyiadvuuwypocxjv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[functions.get-subscription-rpcs]
verify_jwt = true

[functions.cancel-subscription]
verify_jwt = true

