
project_id = "cmzhdyiadvuuwypocxjv"

[functions.generate-ai-workout]
verify_jwt = true

[functions.create-referral-stats-function]
verify_jwt = true

[functions.create-club-event]
verify_jwt = true

[functions.ai-workout-tools]
verify_jwt = true
