
project_id = "cmzhdyiadvuuwypocxjv"

[api]
enabled = true

[functions]
[functions.create-subscription-rpcs]
verify_jwt = true

[functions.cancel-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.refund-request]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
