// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmzhdyiadvuuwypocxjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtemhkeWlhZHZ1dXd5cG9jeGp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxODI0NzYsImV4cCI6MjA1ODc1ODQ3Nn0.HTHID0K9WnXCcYP8JT7L4MUTj8u89ok2uPooSLJFffo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);